pipeline:
branches: dev
  build:
    image: golang:1.7.1
    commands:
      - go get
      - go build
      - go test
  publish:
    image: plugins/docker
    repo: lixw/drone-test
    tags: [ latest, 1, 1.0, 1.0.0 ]
      
